### ISSUE TITLE
still needed with latest Hapi?

### ISSUE THREAD

**Issue by elf-pavlik** [bendrucker/inject-then#18]
https://hapijs.com/api#serverinjectoptions-callback
> If no callback is provided, a Promise object is returned.

I started writing test using inject-then and after reading line above just changed s/injectThen/inject/ and  it worked just the same. Those two release notes mention support for promisses
* 8.0.0 - https://github.com/hapijs/hapi/issues/2186
* 12.0.0 - https://github.com/hapijs/hapi/issues/2985

**Comment by bendrucker** [comment]
It would appear not, I'll cap the peer range appropriate and add a note to the readme when I get a chance.

**Comment by bendrucker** [comment]
Searched back and found it's added in v12
